apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: loadbalancer
type: Opaque
stringData:
  PG_PASSWORD: "postgres"  # Change this to your actual PostgreSQL password
  # REDIS_PASSWORD: ""  # Uncomment and set if Redis password is required


