proxy:
  - name: redis-proxy
    listen: ":6380"
    host: "redis"
    port: 6379
    protocol: tcp

middleware:
  - name: latency
    type: latency
    latency: 100
    jitter: 50
  - name: http-500
    type: http_tamperer
    status: 500
    body: "Chaos Injected"

rules:
  - name: delay-redis
    proxy: redis-proxy
    middleware: 
      - latency
    p: 0.5 # 50% chance



